In [34]:
import pandas as pd
import os
from sqlalchemy import create_engine
from dotenv import load_dotenv

load_dotenv()
engine = create_engine(os.getenv("DATABASE_URL"))

In [35]:
# Queries
query_database_schema = """
    SELECT * 
    FROM information_schema.tables 
    WHERE table_schema = 'public';
"""
query_head="""
    SELECT *
    FROM {}
    LIMIT 10;
"""

query_join_indicators="""
    SELECT *
    FROM indicator_values as v
    INNER JOIN indicators as i
        ON v.indicator_id = i.indicator_id;
"""

query_join_derived_indicators="""
    SELECT *
    FROM derived_values as v
    INNER JOIN derived_indicators as i
        ON v.derived_id = i.derived_id
"""

In [36]:
pd.read_sql_query(query_database_schema, engine)

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,neondb,public,indicators,BASE TABLE,None,None,None,None,None,YES,NO,None
1,neondb,public,indicator_values,BASE TABLE,None,None,None,None,None,YES,NO,None
2,neondb,public,derived_indicators,BASE TABLE,None,None,None,None,None,YES,NO,None
3,neondb,public,derived_values,BASE TABLE,None,None,None,None,None,YES,NO,None

In [37]:
table_names = ["indicator_values", "indicators", "derived_values", "derived_indicators"]
for name in table_names:
    query = query_head.format(name)
    print(f"Table name:{name}")
    display(pd.read_sql_query(query, engine))
    print()

Table name:indicator_values

   id  indicator_id        date  value                inserted_at
0   1             1  2020-01-01    4.5 2026-07-16 20:43:07.186903
1   2             1  2020-01-02    4.5 2026-07-16 20:43:07.186903
2   3             1  2020-01-03    4.5 2026-07-16 20:43:07.186903
3   4             1  2020-01-04    4.5 2026-07-16 20:43:07.186903
4   5             1  2020-01-05    4.5 2026-07-16 20:43:07.186903
5   6             1  2020-01-06    4.5 2026-07-16 20:43:07.186903
6   7             1  2020-01-07    4.5 2026-07-16 20:43:07.186903
7   8             1  2020-01-08    4.5 2026-07-16 20:43:07.186903
8   9             1  2020-01-09    4.5 2026-07-16 20:43:07.186903
9  10             1  2020-01-10    4.5 2026-07-16 20:43:07.186903

Table name:indicators

,indicator_id,external_code,indicator_name,source,frequency,unit,created_at
0,1,432,SELIC Meta,BACEN,daily,%,2026-07-16 20:43:07.186903
1,2,433,IPCA,BACEN,monthly,%,2026-07-16 20:43:09.816268
2,3,13522,IPCA Acumulado 12m,BACEN,monthly,%,2026-07-16 20:43:11.970311
3,4,188,INPC,BACEN,monthly,%,2026-07-16 20:43:15.760453
4,5,189,IGP-M,BACEN,monthly,%,2026-07-16 20:43:17.591924
5,6,24364,IBC-Br,BACEN,monthly,index,2026-07-16 20:43:19.029038
6,7,1,Câmbio USD/BRL,BACEN,daily,R$,2026-07-16 20:43:30.293865
7,8,IBGE_1620_583_90707,PIB Trimestral (índice de volume),IBGE,quarterly,index (1995=100),2026-07-16 20:43:31.331946

Table name:derived_values

   id  derived_id        date  value                inserted_at
0   1           1  2020-01-01    NaN 2026-07-16 20:43:07.629129
1   2           1  2020-01-02    0.0 2026-07-16 20:43:07.629129
2   3           1  2020-01-03    0.0 2026-07-16 20:43:07.629129
3   4           1  2020-01-04    0.0 2026-07-16 20:43:07.629129
4   5           1  2020-01-05    0.0 2026-07-16 20:43:07.629129
5   6           1  2020-01-06    0.0 2026-07-16 20:43:07.629129
6   7           1  2020-01-07    0.0 2026-07-16 20:43:07.629129
7   8           1  2020-01-08    0.0 2026-07-16 20:43:07.629129
8  39           1  2020-02-08    0.0 2026-07-16 20:43:07.629129
9  40           1  2020-02-09    0.0 2026-07-16 20:43:07.629129

Table name:derived_indicators

,derived_id,name,base_indicator_id,formula_desc,created_at
0,1,SELIC Meta_daily_variation,1,Daily Variation of SELIC Meta,2026-07-16 20:43:07.629129
1,2,IPCA_yoy_variation,2,Yoy Variation of IPCA,2026-07-16 20:43:09.876023
2,3,INPC_yoy_variation,4,Yoy Variation of INPC,2026-07-16 20:43:15.825232
3,4,IGP-M_yoy_variation,5,Yoy Variation of IGP-M,2026-07-16 20:43:17.643406
4,5,Câmbio USD/BRL_daily_variation,7,Daily Variation of Câmbio USD/BRL,2026-07-16 20:43:30.653030

In [41]:
df_indicators = pd.read_sql_query(query_join_indicators, engine)
df_derived = pd.read_sql_query(query_join_derived_indicators, engine)
print("Joined indicators table head: ")
print(df_indicators.head())
print()
print("Joined derived indicators table head: ")
print(df_derived.head())

Joined indicators table head:
   id  indicator_id        date  value                inserted_at  \
0   1             1  2020-01-01    4.5 2026-07-16 20:43:07.186903
1   2             1  2020-01-02    4.5 2026-07-16 20:43:07.186903
2   3             1  2020-01-03    4.5 2026-07-16 20:43:07.186903
3   4             1  2020-01-04    4.5 2026-07-16 20:43:07.186903
4   5             1  2020-01-05    4.5 2026-07-16 20:43:07.186903

   indicator_id external_code indicator_name source frequency unit  \
0             1           432     SELIC Meta  BACEN     daily    %
1             1           432     SELIC Meta  BACEN     daily    %
2             1           432     SELIC Meta  BACEN     daily    %
3             1           432     SELIC Meta  BACEN     daily    %
4             1           432     SELIC Meta  BACEN     daily    %

                  created_at
0 2026-07-16 20:43:07.186903
1 2026-07-16 20:43:07.186903
2 2026-07-16 20:43:07.186903
3 2026-07-16 20:43:07.186903
4 2026-07-16 20:43:07.186903

Joined derived indicators table head:
   id  derived_id        date  value                inserted_at  derived_id  \
0   1           1  2020-01-01    NaN 2026-07-16 20:43:07.629129           1
1   2           1  2020-01-02    0.0 2026-07-16 20:43:07.629129           1
2   3           1  2020-01-03    0.0 2026-07-16 20:43:07.629129           1
3   4           1  2020-01-04    0.0 2026-07-16 20:43:07.629129           1
4   5           1  2020-01-05    0.0 2026-07-16 20:43:07.629129           1

                         name  base_indicator_id  \
0  SELIC Meta_daily_variation                  1
1  SELIC Meta_daily_variation                  1
2  SELIC Meta_daily_variation                  1
3  SELIC Meta_daily_variation                  1
4  SELIC Meta_daily_variation                  1

                    formula_desc                 created_at
0  Daily Variation of SELIC Meta 2026-07-16 20:43:07.629129
1  Daily Variation of SELIC Meta 2026-07-16 20:43:07.629129
2  Daily Variation of SELIC Meta 2026-07-16 20:43:07.629129
3  Daily Variation of SELIC Meta 2026-07-16 20:43:07.629129
4  Daily Variation of SELIC Meta 2026-07-16 20:43:07.629129